const fs=require('node:fs'),assert=require('node:assert/strict');
const app=fs.readFileSync('lib/Apps/AppPaperboy/AppPaperboy.cpp','utf8');
const start=app.slice(app.indexOf('void AppPaperboy::start()'),app.indexOf('void AppPaperboy::scan()'));
assert(start.indexOf('gate().pause()')<start.indexOf('gate().idle()'));
assert(start.indexOf('while (!NetworkWork::gate().idle())')<start.indexOf('WiFi.mode(WIFI_OFF)'));
assert.match(start,/while \(!NetworkWork::gate\(\).idle\(\)\) vTaskDelay/);
assert.match(app,/RomStorage::release\(RomStorage::Game\);\s*NetworkWork::gate\(\).resume\(\)/);
const updater=fs.readFileSync('lib/Book32_Update/GitHubMgr.cpp','utf8');
const check=updater.slice(updater.indexOf('UpdateInfo GitHubMgr::checkUpdate'),updater.indexOf('bool GitHubMgr::performFirmwareUpdate'));
assert(check.indexOf('NetworkWork::Lease network')<check.indexOf('WiFiClientSecure client'));
assert(check.indexOf('WiFiClientSecure client')<check.indexOf('HTTPClient http'));
assert(check.includes('if (!network) return info;'));
assert(check.includes('setHandshakeTimeout(5)')&&check.includes('setConnectTimeout(5000)'));
const main=fs.readFileSync('src/main.cpp','utf8');
const menu=fs.readFileSync('lib/Book32_Apps/AppMainMenu.cpp','utf8');
const startup=main.slice(main.indexOf('static void networkStartupWork'),main.indexOf('static void networkStartupTask'));
const wake=menu.slice(menu.indexOf('void AppMainMenu::wifiWakeWork'),menu.indexOf('String AppMainMenu::getWifiFooterText'));
assert(!startup.includes('vTaskDelete')&&!wake.includes('vTaskDelete'));
assert(startup.includes('"Ink Boy"')&&!main.includes('"Paperboy"'));
assert.match(main,/NetworkWork::Lease network;\s*if \(network\) networkStartupWork/);
assert.match(menu,/NetworkWork::Lease network;\s*if \(network\) wifiWakeWork/);
console.log('Network integration PASS: TLS destruction before lease release, drained shutdown, task unwinding, current app name');
