"""Generate compact Adafruit GFX font tables from the bundled Open Sans TTFs."""

from pathlib import Path

from PIL import Image, ImageDraw, ImageFont


ROOT = Path(__file__).resolve().parents[1]
FONT_DIR = ROOT / "Open_Sans" / "static"
OUTPUT = ROOT / "lib" / "Apps" / "AppReader" / "fonts" / "OpenSansGFXFonts.h"
DPI = 141
FIRST_CHAR = 0x20
LAST_CHAR = 0x7E


def pack_bitmap(image: Image.Image) -> list[int]:
    bits = [1 if image.getpixel((x, y)) else 0
            for y in range(image.height) for x in range(image.width)]
    while len(bits) % 8:
        bits.append(0)

    packed = []
    for index in range(0, len(bits), 8):
        value = 0
        for bit in bits[index:index + 8]:
            value = (value << 1) | bit
        packed.append(value)
    return packed


def convert_font(ttf_path: Path, name: str, point_size: int) -> str:
    pixel_size = round(point_size * DPI / 72)
    font = ImageFont.truetype(str(ttf_path), pixel_size)
    ascent, descent = font.getmetrics()
    bitmap = []
    glyphs = []

    for codepoint in range(FIRST_CHAR, LAST_CHAR + 1):
        character = chr(codepoint)
        left, top, right, bottom = font.getbbox(character, anchor="ls")
        width = max(1, right - left)
        height = max(1, bottom - top)
        image = Image.new("1", (width, height), 0)
        ImageDraw.Draw(image).text(
            (-left, -top), character, font=font, fill=1, anchor="ls"
        )

        bounds = image.getbbox()
        offset = len(bitmap)
        if bounds:
            x0, y0, x1, y1 = bounds
            cropped = image.crop(bounds)
            glyph_width = cropped.width
            glyph_height = cropped.height
            x_offset = left + x0
            y_offset = top + y0 + 1
            bitmap.extend(pack_bitmap(cropped))
        else:
            glyph_width = 0
            glyph_height = 0
            x_offset = 0
            y_offset = 0

        x_advance = max(1, round(font.getlength(character)))
        glyphs.append((offset, glyph_width, glyph_height, x_advance,
                       x_offset, y_offset, codepoint, character))

    bitmap_lines = []
    for index in range(0, len(bitmap), 12):
        bitmap_lines.append("  " + ", ".join(
            f"0x{value:02X}" for value in bitmap[index:index + 12]
        ))

    glyph_lines = []
    for offset, width, height, advance, x_offset, y_offset, codepoint, character in glyphs:
        printable = character if character not in {"\\", "'"} else f"\\{character}"
        glyph_lines.append(
            f"  {{ {offset:5d}, {width:3d}, {height:3d}, {advance:3d}, "
            f"{x_offset:4d}, {y_offset:4d} }},  // 0x{codepoint:02X} '{printable}'"
        )

    return f"""const uint8_t {name}Bitmaps[] PROGMEM = {{
{',\n'.join(bitmap_lines)}
}};

const GFXglyph {name}Glyphs[] PROGMEM = {{
{chr(10).join(glyph_lines)}
}};

const GFXfont {name} PROGMEM = {{
  (uint8_t *){name}Bitmaps,
  (GFXglyph *){name}Glyphs,
  0x{FIRST_CHAR:02X}, 0x{LAST_CHAR:02X}, {ascent + descent}
}};
"""


def main() -> None:
    fonts = []
    for weight, filename in (
        ("Regular", "OpenSans-Regular.ttf"),
        ("Bold", "OpenSans-Bold.ttf"),
    ):
        for point_size in (9, 12, 18, 24):
            name = f"OpenSans{weight}{point_size}pt7b"
            fonts.append(convert_font(FONT_DIR / filename, name, point_size))

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(
        "#pragma once\n\n"
        "// Generated by tools/generate_open_sans_gfx.py from Open Sans.\n"
        "// Open Sans is licensed under the SIL Open Font License 1.1.\n"
        "#include <Adafruit_GFX.h>\n\n"
        + "\n".join(fonts),
        encoding="ascii",
    )


if __name__ == "__main__":
    main()
